spring:
  datasource:
    url: jdbc:sqlserver://azurejava.database.windows.net:1433;database=azurejavadb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: azurejava
    password: sqldb@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191